# For Future expansion on output Method : HBASE, PHOENIX, CSV, JSON
OUTPUT_METHOD = 'CSV'
OUTPUT_TO_FILE = True
OUTPUT_FILE_DIR = 'output/'
OUTPUT_FILE_NAME = "pokeWorld_Output"

# HBASE Configs for hbase thrift connections
HBASE_TABLE_NAME = 'POKEMON_TRAINERS'
HBASE_SERVER = 'server.example.com'
HBASE_SERVER_PORT = '13371'

# Phoenix Configs for Phoenix Query Server
# Query Server URI Syntax: http://PHOENIX_QUERY_SERVER:PHOENIX_QUERY_SERVER_PORT
PHOENIX_TABLE_NAME = 'POKEMON'
PHOENIX_QUERY_SERVER = 'server.example.com'
PHOENIX_QUERY_SERVER_PORT = '8765'
PHOENIX_QUERY_SERVER_URI = 'http://' + PHOENIX_QUERY_SERVER + ':' + PHOENIX_QUERY_SERVER_PORT


# TRAINER CONFIGS
MAX_TRAINER_POKEMON_LEVEL = 60
TRAINER_COUNT = 3

# POKEMON CONFIGS
MAX_POKEMON_ID = 151
LOCAL_LANGUAGE_ID = 9
VERSION_GROUP_ID = 1


# Faker Configs
FAKER_SEED_ENABLED = False
FAKER_SEED_VALUE = 1337

